### ISSUE TITLE
Uygulama Çalışıyor ama Test sms bildirimi gelmiyor

### ISSUE THREAD

**Issue by BatuhanYerinde** [cetingokhan/idata_notifier#1]
Uygulama docker üzerinde ayağa kalkıyor. Enviroment ayarını test modda açıyorum ama sms bildirimi düşmüyor.  Sms tarafını twilio tarafında web arayüzünden denediğimde bildirim alabildim.

Idata tarafından gelen veriyi console da görebilmek için logger ekledim ama herhangi bir log göremedim (Scheduler tarafında bir hata yok ama istekler tetiklenmiyormu acaba diye düşündüm). Env değişkenlerini readme tarafındaki gibi ayarladım burdaki ayarlardan başka bir ayar yapmak gerekiyormu?

Not : Mail tarafını disabled ettim o kısmı kullanmıyorum.

**Comment by cetingokhan** [comment]
Alıcı telefon numarasına twilio da kayıt ettiğiniz telefon numarasını girmeniz gerekiyor(free account için) Ayrıca twilio ülke ayarlarından gönderi ülkesinden Türkiye yi seçmeniz gerekiyor.

Aiflow dag 2 dakikalık olarak schedule edilmiş durumda, loglar consolelog da değilde airflow'un ui dan tasklaron loglarını inceleyebilirsiniz; 

http://localhost:8080 
User&pass: airflow

**Comment by BatuhanYerinde** [comment]
Teşekkürler test sms'i geldi. Darısı prod'un başına :)
