### ISSUE TITLE
HTTP 403 Ignoring Response

### ISSUE THREAD

**Issue by altineel** [cetingokhan/idata_notifier#3]
Merhabalar, öncelikle bu repo'yu oluşturduğunuz için teşekkür etmek isterim. 
Ancak ben aşağıdaki 403 Error'uyla karşılaşıyorum çalıştırdığımda. Anlayamadığım diğer bir noktays kodun Captcha'yı nasıl aştığı ? 

[2024-01-05, 11:40:42 UTC] {engine.py:358} DEBUG - Crawled (403) <GET https://deu-schengen.idata.com.tr/tr/appointment-form> (referer: None)
[2024-01-05, 11:40:42 UTC] {httperror.py:57} INFO - Ignoring response <403 https://deu-schengen.idata.com.tr/tr/appointment-form>: HTTP status code is not handled or not allowed

**Comment by cetingokhan** [comment]
Selamlar, bunu yayına alınca iadata cloudflare'i devreye aldı :) yani tüm crawl robotları engelledi. Ben fırsat buldukça cloudflare i aşan toolları deneyip bypass etmeyi deniyorum ama henüz 2 tanesini deneyebildim ve başarısız oldular. Çözdüğümde güncel kodu ekleyeceğim. Şimdilik repoyu follow edebilirsin, güncelleme geldiğinde bildirim alabilirsin ;)

Crawl'ı captha dan sonra başlatıyorum o yüzden sorun olmuyordu ;)

**Comment by altineel** [comment]
> Selamlar, bunu yayına alınca iadata cloudflare'i devreye aldı :) yani tüm crawl robotları engelledi. Ben fırsat buldukça cloudflare i aşan toolları deneyip bypass etmeyi deniyorum ama henüz 2 tanesini deneyebildim ve başarısız oldular. Çözdüğümde güncel kodu ekleyeceğim. Şimdilik repoyu follow edebilirsin, güncelleme geldiğinde bildirim alabilirsin ;)
> 
> Crawl'ı captha dan sonra başlatıyorum o yüzden sorun olmuyordu ;)

Ben de öyle tahmin etmiştim :D. Teşekkürler !!
