### ISSUE TITLE
Airflow-webserver Container'nın Restart döngüsüne Girmesi

### ISSUE THREAD

**Issue by haydar** [cetingokhan/idata_notifier#5]
Öncelikle proje için teşekkürler.

Belgelendirmede yazıldığı gibi projeyi ayağa kaldırdığımda apache airflow containerının fail olduğunu görüyorum. Bu nedenle sürekli restart etmekte. 

İşletim Sistemi : GNU/Linux Ubuntu 22.04 

![Screenshot from 2024-01-18 13-59-47](https://github.com/cetingokhan/idata_notifier/assets/6452942/f7f07dc3-8589-4925-8e39-8d2063e3c622)
![Screenshot from 2024-01-18 14-03-05](https://github.com/cetingokhan/idata_notifier/assets/6452942/eac89fdf-440b-4fe0-b368-03d0d2354205)

**Comment by cetingokhan** [comment]
Selamlar, Oncelikle belirtmeliyim ki; idata cloudflare'i devreye aldigi icin uygulama suan randevu bulmuyor.

Ama bypass icin vakit buldukca denemeye devam ediyorum. Repoyu follow edebilirsin.

Aldigin hataya gelince de; projendeki logs klasorunu sil sonra tekrar baslat, logs klasorune erisemedigi icin hata aliyor gibi gorunuyor ;)
